---
title: "My Example Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


```{r}
set.seed(1)

data("rest_inspec")
inspection_data = 
  rest_inspec %>% 
  select(
    boro, critical_flag, cuisine_description, street, zipcode, grade, score) %>%
  filter(
    !is.na(grade), 
    !is.na(score))%>%
  filter(score>0)%>%
  rename(rest_type = cuisine_description)%>%
  rename(borough = boro) %>%
  mutate(
    rest_type = recode(rest_type, "Café/Coffee/Tea" = "Coffee Shop", 
                       "Latin (Cuban, Dominican, Puerto Rican, South & Central American)" = "Latin")) %>%
  filter(grade == "A"|
        grade == "B"|
        grade == "C") %>%
  sample_n(5000)
```

Column {data-width=600}
-----------------------------------------------------------------------
### Interactive Violinplot of Scores across the 8 Most Common NYC Restaurant Types

```{r}
common_rest =
  inspection_data %>% 
  count(rest_type, sort = TRUE) %>% 
  top_n(8) %>% 
  select(rest_type)

inner_join(inspection_data, common_rest, by = "rest_type") %>% 
  mutate(text_label = str_c("Score", score, 'Grade', grade)) %>% 
  mutate(rest_type = fct_reorder(rest_type, score)) %>% 
  plot_ly(y = ~score, color = ~rest_type, type = "violin",
          colors = "Set2", text = ~text_label)
```


Column {data-width=400}
-----------------------------------------------------------------------
### Dotplot of Grades and Scores By Borough

```{r}
inspect_grades = 
  inspection_data %>%
  mutate(text_label = str_c("Score", score, 'Grade', grade)) %>% 
  plot_ly(
    x = ~score, y = ~borough, type = "scatter", mode = "markers",
    color = ~grade, text = ~text_label, alpha = 0.5)

inspect_grades
```

### The Top 30 NYC Zipcodes by the number of Critical Violations given

```{r}
common_zip =
  inspection_data %>% 
  filter(critical_flag == "Critical") %>%
  count(zipcode, sort = TRUE) %>% 
  top_n(30) %>% 
  select(zipcode)

inner_join(inspection_data, common_zip, by = "zipcode") %>%
  mutate(zipcode = as.factor(zipcode)) %>%
  count(zipcode) %>% 
  mutate(zipcode = fct_reorder(zipcode, n)) %>% 
  rename(critical_violations = n) %>%
  plot_ly(x = ~zipcode, y = ~critical_violations, color = ~zipcode, type = "bar")
```

